---
ID: "dffee92b-0441-45a4-9207-67810b72bd46"
Parent: "895e25c4-12b2-4b2c-8233-82f3b79eef53"
Template: "bc71d442-3e4f-46ba-887c-746e54f9bb83"
Path: /sitecore/system/Settings/Services/Rendering Hosts/Default
BranchID: "00000000-0000-0000-0000-000000000000"
SharedFields:
  - ID: 3121c257-53cf-464a-b736-98b418876057
    Hint: AppName
    Value: healthcare
  - ID: 94470b31-e282-4d8d-bc54-85689efb294c
    Hint: ServerSideRenderingEngineConfigUrl
    Value: "https://xmc-apvosv8mpnzs5n9gsarae-eh.sitecorecloud.io/api/editing/config"
  - ID: 9c6106ea-7a5a-48e2-8cad-f0f693b1e2d4
    Hint: __Read Only
    Value: 1
  - ID: dbbbeca1-21c7-4906-9dd2-493c1efa59a2
    Hint: __Shared revision
    Value: "7ff326f2-0ab3-4fc7-964c-3f0fc40dcef4"
  - ID: e32c1801-79b3-4fc1-a9c4-3c6e6c2968ae
    Hint: ServerSideRenderingEngineApplicationUrl
    Value: "https://xmc-apvosv8mpnzs5n9gsarae-eh.sitecorecloud.io"
  - ID: fc76919b-0d7c-4732-865d-2af795fb38a4
    Hint: ServerSideRenderingEngineEndpointUrl
    Value: "https://xmc-apvosv8mpnzs5n9gsarae-eh.sitecorecloud.io/api/editing/render"
Languages:
  - Language: de-DE
    Fields:
      - ID: 30e85e5d-e00a-4864-b358-7624d511deb4
        Hint: __Unversioned revision
        Value: "{383844E7-4E28-4D45-AE48-640380EF63D8}"
      - ID: b5e02ad9-d56f-4c41-a065-a133db87bdeb
        Hint: __Display name
        Value: Default
    Versions:
      - Version: 1
        Fields:
          - ID: 25bed78c-4957-4165-998a-ca1b52f67497
            Hint: __Created
            Value: 20260119T173622Z
          - ID: 52807595-0f8f-4b20-8d2a-cb71d28c6103
            Hint: __Owner
            Value: |
              sitecore\Admin
          - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
            Hint: __Created by
            Value: |
              sitecore\Admin
          - ID: 8cdc337e-a112-42fb-bbb4-4143751e123f
            Hint: __Revision
            Value: "{1EB7272F-8314-463E-A3CD-0FE6977E5E53}"
          - ID: badd9cf9-53e0-4d0c-bcc0-2d784c282f6a
            Hint: __Updated by
            Value: |
              sitecore\Admin
          - ID: d9cf14b1-fa16-4ba6-9288-e8a174d4d522
            Hint: __Updated
            Value: 20260119T173622Z
  - Language: en
    Fields:
      - ID: 30e85e5d-e00a-4864-b358-7624d511deb4
        Hint: __Unversioned revision
        Value: "60e88e6a-209a-4586-88a8-5bd47a943185"
    Versions:
      - Version: 1
        Fields:
          - ID: 25bed78c-4957-4165-998a-ca1b52f67497
            Hint: __Created
            Value: 20220614T103029Z
          - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
            Hint: __Created by
            Value: |
              sitecore\Admin
          - ID: 8cdc337e-a112-42fb-bbb4-4143751e123f
            Hint: __Revision
            Value: "cf118213-6716-43dc-9947-8e7b60a3a991"
          - ID: badd9cf9-53e0-4d0c-bcc0-2d784c282f6a
            Hint: __Updated by
            Value: |
              sitecore\Anonymous
          - ID: d9cf14b1-fa16-4ba6-9288-e8a174d4d522
            Hint: __Updated
            Value: 20260202T230401Z
      - Version: 1
        Fields:
          - ID: 25bed78c-4957-4165-998a-ca1b52f67497
            Hint: __Created
            Value: 20220614T103029Z
          - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
            Hint: __Created by
            Value: |
              sitecore\Admin
          - ID: 8cdc337e-a112-42fb-bbb4-4143751e123f
            Hint: __Revision
            Value: "cf118213-6716-43dc-9947-8e7b60a3a991"
          - ID: badd9cf9-53e0-4d0c-bcc0-2d784c282f6a
            Hint: __Updated by
            Value: |
              sitecore\Anonymous
          - ID: d9cf14b1-fa16-4ba6-9288-e8a174d4d522
            Hint: __Updated
            Value: 20260202T230401Z
  - Language: es-ES
    Versions:
      - Version: 1
        Fields:
          - ID: 25bed78c-4957-4165-998a-ca1b52f67497
            Hint: __Created
            Value: 20260120T210617Z
          - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
            Hint: __Created by
            Value: |
              sitecore\Anonymous
          - ID: 8cdc337e-a112-42fb-bbb4-4143751e123f
            Hint: __Revision
            Value: "d00aeb48-4172-440b-95d9-0c5cf99a1347"
          - ID: badd9cf9-53e0-4d0c-bcc0-2d784c282f6a
            Hint: __Updated by
            Value: |
              sitecore\Anonymous
          - ID: d9cf14b1-fa16-4ba6-9288-e8a174d4d522
            Hint: __Updated
            Value: 20260120T210617Z
  - Language: fr-FR
    Versions:
      - Version: 1
        Fields:
          - ID: 25bed78c-4957-4165-998a-ca1b52f67497
            Hint: __Created
            Value: 20260120T210617Z
          - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
            Hint: __Created by
            Value: |
              sitecore\Anonymous
          - ID: 8cdc337e-a112-42fb-bbb4-4143751e123f
            Hint: __Revision
            Value: "14472d04-4029-41e8-884a-c5a1b56b91e5"
          - ID: badd9cf9-53e0-4d0c-bcc0-2d784c282f6a
            Hint: __Updated by
            Value: |
              sitecore\Anonymous
          - ID: d9cf14b1-fa16-4ba6-9288-e8a174d4d522
            Hint: __Updated
            Value: 20260120T210617Z
  - Language: ja-JP
    Fields:
      - ID: 30e85e5d-e00a-4864-b358-7624d511deb4
        Hint: __Unversioned revision
        Value: "{383844E7-4E28-4D45-AE48-640380EF63D8}"
      - ID: b5e02ad9-d56f-4c41-a065-a133db87bdeb
        Hint: __Display name
        Value: デフォルト
    Versions:
      - Version: 1
        Fields:
          - ID: 25bed78c-4957-4165-998a-ca1b52f67497
            Hint: __Created
            Value: 20260119T173622Z
          - ID: 52807595-0f8f-4b20-8d2a-cb71d28c6103
            Hint: __Owner
            Value: |
              sitecore\Admin
          - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
            Hint: __Created by
            Value: |
              sitecore\Admin
          - ID: 8cdc337e-a112-42fb-bbb4-4143751e123f
            Hint: __Revision
            Value: "{1EB7272F-8314-463E-A3CD-0FE6977E5E53}"
          - ID: badd9cf9-53e0-4d0c-bcc0-2d784c282f6a
            Hint: __Updated by
            Value: |
              sitecore\Admin
          - ID: d9cf14b1-fa16-4ba6-9288-e8a174d4d522
            Hint: __Updated
            Value: 20260119T173622Z
  - Language: zh-CN
    Fields:
      - ID: 30e85e5d-e00a-4864-b358-7624d511deb4
        Hint: __Unversioned revision
        Value: "{383844E7-4E28-4D45-AE48-640380EF63D8}"
      - ID: b5e02ad9-d56f-4c41-a065-a133db87bdeb
        Hint: __Display name
        Value: 默认
    Versions:
      - Version: 1
        Fields:
          - ID: 25bed78c-4957-4165-998a-ca1b52f67497
            Hint: __Created
            Value: 20260119T173622Z
          - ID: 52807595-0f8f-4b20-8d2a-cb71d28c6103
            Hint: __Owner
            Value: |
              sitecore\Admin
          - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
            Hint: __Created by
            Value: |
              sitecore\Admin
          - ID: 8cdc337e-a112-42fb-bbb4-4143751e123f
            Hint: __Revision
            Value: "{1EB7272F-8314-463E-A3CD-0FE6977E5E53}"
          - ID: badd9cf9-53e0-4d0c-bcc0-2d784c282f6a
            Hint: __Updated by
            Value: |
              sitecore\Admin
          - ID: d9cf14b1-fa16-4ba6-9288-e8a174d4d522
            Hint: __Updated
            Value: 20260119T173622Z
DB: master
