/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/brands/v1/organizations/{organizationId}/brandkits": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List brand kits
     * @description Retrieves a list of brand kits in an organization. The response includes basic information about each brand kit, such as its name, description, industry, and status. The response does not include the actual content of the brand kit sections or subsections.
     */
    get: operations["list_brand_kits"];
    put?: never;
    /**
     * Create a brand kit
     * @description Creates a new brand kit for an organization. The created brand kit includes predefined sections like *Brand Context*, *Global Goals*, *Tone of Voice*, and more, which are empty by default.
     *
     *      In the response, the `id` key contains the created brand kit's unique identifier.
     */
    post: operations["create_brand_kit"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/brands/v1/organizations/{organizationId}/brandkits/{brandkitId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Retrieve a brand kit
     * @description Retrieves a specific brand kit by its ID. The response includes basic information about the brand kit, such as its name, description, industry, and status. The response does not include the actual content of the brand kit sections or subsections.
     *
     *      If you don't know the brand kit ID, you can use the [List brand kits](#operation/list_brand_kits) endpoint to retrieve the list of brand kits in your organization.
     */
    get: operations["get_brand_kit"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/brands/v1/organizations/{organizationId}/brandkits/{brandkitId}/sections": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List brand kit sections
     * @description Retrieves a list of sections in a brand kit. Each section contains information that define the brand's identity and guidelines, such as *Brand Context*, *Global Goals*, and *Tone of Voice*.
     *
     *      To return actual content in the sections, the [Documents REST API](https://api-docs.sitecore.com/ai-skills/ai-document-management-rest-api) and [Pipeline REST API](https://api-docs.sitecore.com/ai-skills/ai-pipeline-rest-api) must have already been used to upload and process brand documents for the brand kit.
     */
    get: operations["list_brand_kit_sections"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/brands/v2/organizations/{organizationId}/brandkits/{brandkitId}/sections/{sectionId}/fields": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List brand kit subsections
     * @description Retrieves a list of subsections (fields) in a specific brand kit section. Each subsection contains guidelines that define that section's content. For example, the *Brand Context* section has subsections to define the brand's purpose, history, and more.
     *
     *      To return actual content in the subsections, the [Documents REST API](https://api-docs.sitecore.com/ai-skills/ai-document-management-rest-api) and [Pipeline REST API](https://api-docs.sitecore.com/ai-skills/ai-pipeline-rest-api) must have already been used to upload and process brand documents for the brand kit.
     */
    get: operations["list_brand_kit_section_fields"];
    put?: never;
    /**
     * Create a brand kit subsection
     * @description Creates a custom brand kit subsection (field). Each brand kit section contains predefined subsections. If a relevant guideline isn’t included by default, you can create a custom subsection to define it. For example, the *Brand Context* section has default subsections to define the brand's purpose, history, and more. To add a new subsection for *Brand Values*, you can use this endpoint to create it.
     *
     *      You can also use this endpoint to manage the terms in the **Glossary and Localization** section as follows:
     *
     *      To add new terms, add a value array. In the following example, *product* will be translated into French and Spanish. {% code-snippet file="../../ai-skills/code-examples/translate-a-term.json" language="json" /%}
     *
     *     **NOTE**: To delete a term, use the [**PATCH** endpoint](#operation/update_brand_kit_section_field).
     *
     *     To mark a term as not to be translated, use an empty value [ ]. In the following example, *CompanyName* will not be translated. {% code-snippet file="../../ai-skills/code-examples/do-not-translate.json" language="json" /%}
     *
     *      **NOTE**: These examples apply only to the **Glossary and Localization** section.
     */
    post: operations["create_brand_kit_section_field"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/brands/v2/organizations/{organizationId}/brandkits/{brandkitId}/sections/{sectionId}/fields/{fieldId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * Partially update a brand kit subsection
     * @description Partially updates a specific subsection (field) in a brand kit.
     *
     *      A brand kit includes default sections such as *Brand Context*, *Global Goals*, and *Tone of Voice*. Each section contains predefined subsections that reflect your brand guidelines.
     *
     *      Use this endpoint to update the properties of a subsection, such as intent, content, and AI editability. You can also use this endpoint to delete locale term values from the **Glossary and Localization** section.
     */
    patch: operations["update_brand_kit_section_field"];
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * BrandKitSectionFieldReferenceType
     * @description The type of reference associated with a brand kit subsection (field).
     * @example documentChunk
     * @enum {string}
     */
    BrandKitSectionFieldReferenceType: "documentChunk" | "webpage";
    /**
     * BrandKitSectionFieldType
     * @description The type of brand kit subsection.
     * @example text
     * @enum {string}
     */
    BrandKitSectionFieldType: "text" | "array" | "richArray";
    /**
     * BrandKitStatus
     * @description The current status of the brand kit.
     * @example draft
     * @enum {string}
     */
    BrandKitStatus: "draft" | "inprocess" | "published" | "failed";
    /** CreateBrandKitModelRequest */
    CreateBrandKitModelRequest: {
      /**
       * Name
       * @description The name of the brand kit.
       * @example Powerful EU brand kit
       */
      name: string;
      /**
       * Description
       * @description A brief description of the brand kit.
       * @example Brand kit for the Powerful energy bars EU market.
       */
      description?: string | null;
      /**
       * Industry
       * @description The industry this brand kit is associated with.
       * @example retail
       */
      industry?: string | null;
      /**
       * Brandname
       * @description The name of the brand associated with this brand kit.
       * @example Powerful
       */
      brandName?: string | null;
      /**
       * Companyname
       * @description The name of the company if different from the brand name.
       * @example Powerful Europe Ltd.
       */
      companyName?: string | null;
      /**
       * Logo
       * @description The URL of the PNG image used as the brand kit logo.
       * @example https://example.com/logo.png
       */
      logo?: string | null;
    };
    /** CreateBrandKitModelResponse */
    CreateBrandKitModelResponse: {
      /**
       * Organizationid
       * @description The unique identifier of your organization.
       * @example org_ABCDef123456
       */
      organizationId: string;
      /**
       * Id
       * @description The unique identifier of the brand kit.
       * @example a1234bcd-efg5-678h-910i-jklmnopqrstu
       */
      id: string;
      /**
       * Description
       * @description A brief description of the brand kit.
       * @example Brand kit for the Powerful energy bars EU market.
       */
      description?: string | null;
      /**
       * Name
       * @description The name of the brand kit.
       * @example Powerful EU brand kit
       */
      name: string;
      /**
       * Brandname
       * @description The name of the brand associated with this brand kit.
       * @example Powerful
       */
      brandName?: string | null;
      /**
       * Companyname
       * @description The name of the company if different from the brand name.
       * @example Powerful Europe Ltd.
       */
      companyName?: string | null;
      /**
       * Logo
       * @description The URL of the PNG image used as the brand kit logo.
       * @example https://example.com/logo.png
       */
      logo?: string | null;
      /** @default draft */
      status: components["schemas"]["BrandKitStatus"] | null;
      /**
       * Parentid
       * @description The parent brand kit ID. Used when AI creates a new version of the brand kit during brand ingestion to indicate the original brand kit it's based on.
       * @example a1234bcd-efg5-678h-910i-abcdefghijklmn
       */
      parentId?: string | null;
      /**
       * @description The type of parent this brand kit belongs to.
       * @default
       * @example brandkit
       */
      parentType: components["schemas"]["ParentTypeEnum"] | null;
      /**
       * Industry
       * @description The industry this brand kit is associated with.
       * @example retail
       */
      industry?: string | null;
      /**
       * Tags
       * @description An array of tags associated with the brand kit to categorize its documents.
       * @example []
       */
      tags?: components["schemas"]["TagList"][] | null;
      /**
       * References
       * @description An array of references associated with the brand kit.
       * @example []
       */
      references?: components["schemas"]["CreateReferenceModelResponse"][] | null;
      /**
       * Createdon
       * @description The date and time when the brand kit was created, formatted in ISO 8601.
       * @example 2025-06-18T12:46:12.718310Z
       */
      createdOn?: string | null;
      /**
       * Createdby
       * @description The user who created the brand kit.
       * @example mman
       */
      createdBy?: string | null;
      /**
       * Updatedon
       * @description The date and time when the brand kit was last updated, formatted in ISO 8601.
       * @example 2025-06-18T12:46:12.718310Z
       */
      updatedOn?: string | null;
      /**
       * Updatedby
       * @description The user who last updated the brand kit, formatted in ISO 8601.
       * @example mman
       */
      updatedBy?: string | null;
    };
    /** CreateBrandKitSectionFieldModelRequest_v2 */
    CreateBrandKitSectionFieldModelRequest_v2: {
      /**
       * Name
       * @description The name of the subsection to be created.
       * @example Localization and cultural sensitivity
       */
      name: string;
      type: components["schemas"]["BrandKitSectionFieldType"];
      /**
       * Order
       * @description The position of the subsection within the brand kit section. For example, in the *Global Goals* section, the `order` is `1` for the *Digital mandatories* subsection.
       * @example 1
       */
      order?: number | null;
      /**
       * Value
       * @description The value or content of the created subsection.
       * @example Essential requirements for adapting digital content to diverse linguistic, cultural, and regional contexts.
       */
      value?:
        | string
        | {
            [key: string]: unknown;
          }
        | unknown[]
        | null;
      /**
       * Intent
       * @description The intent or prompt that instructs the AI in populating this subsection and retrieving information from existing brand knowledge based on uploaded brand documents.
       * @example The core reason for the brand existence.
       */
      intent?: string | null;
      /**
       * References
       * @description An array of references associated with the brand kit subsection.
       */
      references?:
        | components["schemas"]["CreateBrandKitSectionFieldReferenceModelRequest"][]
        | null;
      /**
       * Deletable
       * @description Whether the subsection can be deleted.
       * @default false
       * @example true
       */
      deletable: boolean | null;
      /**
       * Verified
       * @description Whether the subsection's content has been verified by the user.
       * @example true
       */
      verified?: boolean | null;
      /**
       * Aieditable
       * @description Whether the subsection can be edited by AI. If set to `true`, the AI will overwrite the subsection's content value when brand documents are reprocessed.
       * @example true
       */
      aiEditable?: boolean | null;
      /**
       * Createdby
       * @description The user who created the subsection.
       * @example mman
       */
      createdBy?: string | null;
      /**
       * Properties
       * @description Additional properties for the subsection.
       */
      properties?: {
        [key: string]: unknown;
      } | null;
    };
    /** CreateBrandKitSectionFieldModelResponse_v2 */
    CreateBrandKitSectionFieldModelResponse_v2: {
      /**
       * @description The unique identifier for the created brand kit subsection.
       * @example b2f2e1a1-295d-4d40-88f2-93bf545bb879
       */
      id: string;
      /**
       * Name
       * @description The name of the subsection.
       * @example Localization and cultural sensitivity
       */
      name: string;
      type: components["schemas"]["BrandKitSectionFieldType"];
      /**
       * Order
       * @description The order the subsection appears in the brand kit section. For example, if it is the first subsection,  `order` is `1`.
       * @example 1
       */
      order?: number | null;
      /**
       * Value
       * @description The value or content of the created subsection.
       * @example Essential requirements for adapting digital content to diverse linguistic, cultural, and regional contexts.
       */
      value?:
        | string
        | {
            [key: string]: unknown;
          }
        | unknown[]
        | null;
      /**
       * Intent
       * @description The intent or prompt that instructs the AI in populating this subsection and retrieving information from existing brand knowledge based on uploaded brand documents.
       * @example The core reason for the brand existence.
       */
      intent?: string | null;
      /**
       * References
       * @description The brand documents the AI referenced to generate content for this subsection.
       */
      references?: components["schemas"]["CreateReferenceModelResponse"][] | null;
      /**
       * Deletable
       * @description Whether the subsection can be deleted.
       * @default false
       * @example true
       */
      deletable: boolean | null;
      /**
       * Verified
       * @description Whether the subsection's content has been verified by the user.
       * @example true
       */
      verified?: boolean | null;
      /**
       * Createdon
       * Format: date-time
       * @description The date and time when the subsection was created, formatted in ISO 8601.
       * @example 2025-06-18T12:46:12.718310Z
       */
      createdOn?: string | null;
      /**
       * Createdby
       * @description The user who created the subsection
       * @example mman
       */
      createdBy?: string | null;
      /**
       * Updatedon
       * @description The date and time when the subsection was updated, formatted in ISO 8601.
       * @example 2025-06-18T12:46:12.718310Z
       */
      updatedOn?: string | null;
      /**
       * Updatedby
       * @description The user who last updated the subsection.
       * @example mman
       */
      updatedBy?: string | null;
      /**
       * Aieditable
       * @description Whether the subsection can be edited by AI. If set to `true`, the AI will overwrite the subsection's content value when brand documents are reprocessed.
       * @example true
       */
      aiEditable?: boolean | null;
      /**
       * Properties
       * @description Additional properties for the subsection.
       */
      properties?: {
        [key: string]: unknown;
      } | null;
    };
    /** CreateBrandKitSectionFieldReferenceModelRequest */
    CreateBrandKitSectionFieldReferenceModelRequest: {
      /**
       * Id
       * @description The unique identifier of the document used in the brand kit subsection.
       * @example 2ad5c154-6404-49ed-9ffc-0603c360a5af
       */
      id: string;
      /**
       * Path
       * @description The location of the reference used in the brand kit subsection.
       * @example /path
       */
      path: string;
      type: components["schemas"]["BrandKitSectionFieldReferenceType"];
    };
    /** CreateReferenceModelResponse */
    CreateReferenceModelResponse: {
      /**
       * Id
       * @description The unique identifier of the document used in the brand kit.
       * @example 2ad5c154-6404-49ed-9ffc-0603c360a5af
       */
      id: string;
      /**
       * Path
       * @description The location of the reference used in the brand kit.
       * @example /path
       */
      path: string;
      /**
       * Type
       * @description The type of reference used in the brand kit.
       * @example document
       */
      type: string;
    };
    /** DataList */
    DataList: {
      /**
       * Organizationid
       * @description The unique identifier of your organization.
       * @example org_ABCDef123456
       */
      organizationId: string;
      /**
       * Id
       * @description The unique identifier of the brand kit.
       * @example a1234bcd-efg5-678h-910i-jklmnopqrstu
       */
      id: string;
      /**
       * @description A brief description of the brand kit.
       * @example Brand kit for the Powerful energy bars EU market.
       */
      description?: string | null;
      /**
       * @description The name of the brand kit.
       * @example Powerful EU brand kit
       */
      name: string;
      /**
       * Brandname
       * @description The name of the brand associated with this brand kit.
       * @example Powerful
       */
      brandName?: string | null;
      /**
       * Companyname
       * @description The name of the company if different from the brand name.
       * @example Powerful Europe Ltd.
       */
      companyName?: string | null;
      /**
       * Logo
       * @description The URL of the PNG image used as the brand kit logo.
       * @example https://example.com/logo.png
       */
      logo?: string | null;
      /**
       * Status
       * @description The current status of the brand kit.
       * @example Draft
       */
      status?: string | null;
      /**
       * Parentid
       * @description The parent brand kit ID. Used when AI creates a new version of the brand kit during brand ingestion to indicate the original brand kit it's based on.
       * @example a1234bcd-efg5-678h-910i-abcdefghijklmn
       */
      parentId?: string | null;
      /**
       * Parenttype
       * @description The type of parent this brand kit belongs to.
       * @example brandkit
       */
      parentType?: string | null;
      /**
       * Industry
       * @description The industry this brand kit is associated with.
       * @example retail
       */
      industry?: string | null;
      /**
       * Createdon
       * Format: date-time
       * @description The date and time when the brand kit was created, formatted in ISO 8601.
       * @example 2025-06-18T12:46:12.718310Z
       */
      createdOn?: string | null;
      /**
       * Createdby
       * @description The user who created the brand kit.
       * @example mman
       */
      createdBy?: string | null;
      /**
       * Updatedon
       * @description The date and time when the brand kit was last updated, formatted in ISO 8601.
       * @example 2025-06-18T12:46:12.718310Z
       */
      updatedOn?: string | null;
      /**
       * Updatedby
       * @description The user who last updated the brand kit, formatted in ISO 8601.
       * @example mman
       */
      updatedBy?: string | null;
      /**
       * Tags
       * @description An array of tags associated with the brand kit to categorize its documents.
       * @default []
       * @example []
       */
      tags: components["schemas"]["TagList"][] | null;
      /**
       * References
       * @description An array of references associated with the brand kit.
       * @default []
       * @example []
       */
      references: components["schemas"]["ListReferencesModelResponseData"][] | null;
      /**
       * Deletedat
       * @description The date and time when the brand kit was deleted, formatted in ISO 8601.
       * @example 2025-06-18T12:46:12.718310Z
       */
      deletedAt?: string | null;
    };
    /** DuplicateError */
    DuplicateError: {
      /** Detail */
      detail: string;
      /**
       * Loc
       * @default [
       *       "body",
       *       "name"
       *     ]
       */
      loc: string[];
      /**
       * Msg
       * @default Brand name already exists.
       */
      msg: string;
      /**
       * Type
       * @default value_error.duplicate
       */
      type: string;
    };
    /** DuplicateHTTPError */
    DuplicateHTTPError: {
      /** Detail */
      detail: components["schemas"]["DuplicateError"][];
    };
    /** GetBrandKitModelResponse */
    GetBrandKitModelResponse: {
      /**
       * Organizationid
       * @description The unique identifier of your organization.
       * @example org_ABCDef123456
       */
      organizationId: string;
      /**
       * Id
       * @description The unique identifier of the brand kit.
       * @example a1234bcd-efg5-678h-910i-jklmnopqrstu
       */
      id: string;
      /**
       * Description
       * @description A brief description of the brand kit.
       * @example Brand kit for the Powerful energy bars EU market.
       */
      description?: string | null;
      /**
       * Name
       * @description The name of the brand kit.
       * @example Powerful EU brand kit
       */
      name: string;
      /**
       * Brandname
       * @description The name of the brand associated with this brand kit.
       * @example Powerful
       */
      brandName?: string | null;
      /**
       * Companyname
       * @description The name of the company if different from the brand name.
       */
      companyName?: string | null;
      /**
       * Logo
       * @description The URL of the PNG image used as the brand kit logo.
       * @example https://example.com/logo.png
       */
      logo?: string | null;
      /**
       * Status
       * @description The current status of the brand kit.
       * @example Draft
       */
      status?: string | null;
      /**
       * Parentid
       * @description The parent brand kit ID. Used when AI creates a new version of the brand kit during brand ingestion to indicate the original brand kit it's based on.
       * @example a1234bcd-efg5-678h-910i-abcdefghijklmn
       */
      parentId?: string | null;
      /**
       * Parenttype
       * @description The type of parent this brand kit belongs to.
       * @example brandkit
       */
      parentType?: string | null;
      /**
       * Industry
       * @description The industry this brand kit is associated with.
       * @example retail
       */
      industry?: string | null;
      /**
       * Createdon
       * @description The date and time when the brand kit was created, formatted in ISO 8601.
       * @example 2025-06-18T12:46:12.718310Z
       */
      createdOn?: string | null;
      /**
       * Createdby
       * @description The user who created the brand kit.
       * @example mman
       */
      createdBy?: string | null;
      /**
       * Updatedon
       * @description The date and time when the brand kit was last updated, formatted in ISO 8601.
       * @example 2025-06-18T12:46:12.718310Z
       */
      updatedOn?: string | null;
      /**
       * Updatedby
       * @description The user who last updated the brand kit, formatted in ISO 8601.
       * @example mman
       */
      updatedBy?: string | null;
      /**
       * Tags
       * @description An array of tags associated with the brand kit to categorize its documents.
       * @example []
       */
      tags: components["schemas"]["TagList"][] | null;
      /**
       * References
       * @description An array of references associated with the brand kit.
       * @example []
       */
      references: components["schemas"]["GetReferenceModelResponse"][] | null;
      /**
       * Deletedat
       * @description The date and time when the brand kit was deleted, if applicable, formatted in ISO 8601.
       * @example 2025-06-18T12:46:12.718310Z
       */
      deletedAt?: string | null;
      /**
       * Locked
       * @description Whether the brand kit is locked. A locked brand kit cannot be modified or deleted.
       * @default false
       * @example false
       */
      locked: boolean | null;
    };
    GetReferenceModelResponse: {
      /**
       * Id
       * @description The unique identifier of the reference document.
       * @example 2ad5c154-6404-49ed-9ffc-0603c360a5af
       */
      id: string;
      /**
       * Path
       * @description The location of the reference.
       * @example /path
       */
      path: string;
      /**
       * Type
       * @description The type of reference used.
       * @example document
       */
      type: string;
    };
    /** HTTPError */
    HTTPError: {
      /** Detail */
      detail: string;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** ListBrandKitSectionFieldsModelResponse_v2 */
    ListBrandKitSectionFieldsModelResponse_v2: {
      /**
       * Id
       * @description The unique identifier of the brand kit subsection.
       * @example b2f2e1a1-295d-4d40-88f2-93bf545bb878
       */
      id: string;
      /**
       * Name
       * @description The name of the subsection in the brand kit.
       * @example Brand purpose
       */
      name: string;
      type: components["schemas"]["BrandKitSectionFieldType"];
      /**
       * Order
       * @description The position of the subsection within the brand kit section. For example, in the *Global Goals* section, the `order` is `1` for the *Digital mandatories* subsection.
       * @example 1
       */
      order?: number | null;
      /**
       * Value
       * @description The content of the subsection in the brand kit section. This can be a string, an array, or a rich text object.
       * @example The core reason for the brand existence is to fuel the potential of active individuals with clean, nutrient-dense energy solutions.
       */
      value?:
        | string
        | {
            [key: string]: unknown;
          }
        | unknown[]
        | null;
      /**
       * Intent
       * @description The intent or prompt that instructs the AI in populating this subsection and retrieving information from existing brand knowledge based on uploaded brand documents.
       * @example The core reason for the brand existence.
       */
      intent?: string | null;
      /**
       * References
       * @description An array of references used in this subsection. Each reference points to a brand document that provides context or content for the subsection.
       * @example []
       */
      references?: components["schemas"]["ListReferencesModelResponseData"][] | null;
      /**
       * Deletable
       * @description Whether the subsection can be deleted.
       * @example true
       */
      deletable?: boolean | null;
      /**
       * Verified
       * @description Whether the subsection's content has been verified by the user.
       * @example true
       */
      verified?: boolean | null;
      /**
       * Createdon
       * @description The date and time when the subsection was created, formatted in ISO 8601.
       * @example 2025-06-18T12:46:12.718310Z
       */
      createdOn?: string | null;
      /**
       * Createdby
       * @description The user who created the subsection.
       * @example mman
       */
      createdBy?: string | null;
      /**
       * Updatedon
       * @description The date and time when the subsection was last updated, formatted in ISO 8601.
       * @example 2025-06-18T12:46:12.718310Z
       */
      updatedOn?: string | null;
      /**
       * Updatedby
       * @description The user who last updated the subsection.
       * @example mman
       */
      updatedBy?: string | null;
      /**
       * Aieditable
       * @description Whether the subsection can be edited by AI. If set to `true`, the AI will overwrite the subsection's content when brand documents are reprocessed.
       * @example true
       */
      aiEditable?: boolean | null;
      /**
       * Properties
       * @description Additional properties for the subsection.
       */
      properties?: {
        [key: string]: unknown;
      } | null;
    };
    /** ListBrandKitSectionsModelResponse */
    ListBrandKitSectionsModelResponse: {
      /**
       * Deletable
       * @description Whether the section can be deleted.
       * @example true
       */
      deletable?: boolean | null;
      /**
       * Id
       * @description The unique identifier of the brand kit section.
       * @example 37a49437-e1c8-4697-b1c2-914e2382ea75
       */
      id: string;
      /**
       * Name
       * @description The name of the brand kit section.
       * @example Brand Context
       */
      name: string;
      /**
       * Order
       * @description The position of the section within the brand kit. For example, if *Global Goals* is the first section, its `order` is `1`. If *Brand Context* is second, `order` is `2`, and so on.
       * @example 2
       */
      order?: number | null;
      /**
       * Createdon
       * @description The date and time when the section was created, formatted in ISO 8601.
       * @example 2025-06-18T12:46:12.718310Z
       */
      createdOn?: string | null;
      /**
       * Createdby
       * @description The user who created the section.
       * @example mman
       */
      createdBy?: string | null;
      /**
       * Updatedon
       * @description The date and time when the section was last updated, formatted in ISO 8601.
       * @example 2025-06-18T12:46:12.718310Z
       */
      updatedOn?: string | null;
      /**
       * Updatedby
       * @description The user who last updated the section.
       * @example mman
       */
      updatedBy?: string | null;
      /**
       * Deletedat
       * @description The date and time when the section was deleted, if applicable, formatted in ISO 8601.
       * @example 2025-06-18T12:46:12.718310Z
       */
      deletedAt?: string | null;
      /**
       * Properties
       * @description Additional properties for the section.
       */
      properties?: {
        [key: string]: unknown;
      } | null;
    };
    /** ListBrandKitsModelResponse */
    ListBrandKitsModelResponse: {
      /**
       * Totalcount
       * @description The total number of brand kits available in the organization.
       * @example 10
       */
      totalCount: number;
      /**
       * Pagesize
       * @description The number of brand kits returned per page.
       * @example 5
       */
      pageSize: number;
      /**
       * Pagenumber
       * @description The current page number of the brand kits list.
       * @example 1
       */
      pageNumber: number;
      /**
       * Data
       * @description An array of brand kits available in the organization.
       */
      data: components["schemas"]["DataList"][];
    };
    ListReferencesModelResponseData: {
      /**
       * Id
       * @description The unique identifier of the reference document.
       * @example 2ad5c154-6404-49ed-9ffc-0603c360a5af
       */
      id: string;
      /**
       * Path
       * @description The location of the reference.
       * @example /path
       */
      path: string;
      /**
       * Type
       * @description The type of reference used.
       * @example document
       */
      type: string;
    };
    /**
     * ParentTypeEnum
     * @description The type of the parent entity that the tags are associated with. This can be used to categorize tags based on the specific entity they are linked to, such as a brand kit, section, or subsection.
     * @enum {string}
     */
    ParentTypeEnum: "brandkit" | "";
    /**
     * SortByEnum
     * @description The field by which to sort the brand kits. This can be based on the creation date (`createdOn`) or the last updated date (`updatedOn`).
     * @example createdOn
     * @enum {string}
     */
    SortByEnum: "createdOn" | "updatedOn";
    /**
     * SortTypeEnum
     * @description The order in which to sort the brand kits. This can be either ascending (`asc`) or descending (`desc`).
     * @example asc
     * @enum {string}
     */
    SortTypeEnum: "asc" | "desc";
    /** TagList */
    TagList: {
      /**
       * @description The main grouping or classification applied to the brand kit.
       * @example audience
       */
      category: string;
      values: string[];
    };
    /** UpdateBrandKitSectionFieldModelRequest_v2 */
    UpdateBrandKitSectionFieldModelRequest_v2: {
      /**
       * Deletable
       * @description Whether the subsection can be deleted.
       * @default false
       * @example false
       */
      deletable: boolean | null;
      /**
       * Name
       * @description The name of the subsection to be updated.
       * @example Brand purpose
       */
      name?: string | null;
      /**
       * Verified
       * @description Whether the subsection's content has been verified by the user.
       * @example true
       */
      verified?: boolean | null;
      /**
       * Order
       * @description The position of the subsection within the brand kit section. For example, in the *Global Goals* section, the `order` is `1` for the *Digital mandatories* subsection.
       * @example 1
       */
      order?: number | null;
      /**
       * Value
       * @description The new content of the subsection in the brand kit section.
       * @example The core purpose is to fuel the potential of active individuals with clean, nutrient-dense energy solutions.
       */
      value?:
        | string
        | {
            [key: string]: unknown;
          }
        | unknown[]
        | null;
      /**
       * Intent
       * @description The intent or prompt that instructs the AI in populating this subsection and retrieving information from existing brand knowledge based on uploaded brand documents.
       * @example The core reason for the brand existence.
       */
      intent?: string | null;
      /**
       * Sources
       * @description The brand documents the AI referenced to generate content for this subsection.
       */
      sources?: string[] | null;
      /**
       * Aieditable
       * @description Whether the subsection can be edited by AI. If set to `true`, the AI will overwrite the subsection's content value when brand documents are reprocessed.
       * @example true
       */
      aiEditable?: boolean | null;
      /**
       * Updatedby
       * @description The user who last updated the subsection.
       * @example mman
       */
      updatedBy?: string | null;
      /**
       * Properties
       * @description Additional properties for the subsection.
       */
      properties?: {
        [key: string]: unknown;
      } | null;
    };
    /** UpdateBrandKitSectionFieldModelResponse_v2 */
    UpdateBrandKitSectionFieldModelResponse_v2: {
      /**
       * Id
       * @description The unique identifier of the updated brand kit subsection.
       * @example b2f2e1a1-295d-4d40-88f2-93bf545bb878
       */
      id: string;
      /**
       * Name
       * @description The name of the subsection.
       * @example Brand purpose
       */
      name: string;
      type: components["schemas"]["BrandKitSectionFieldType"];
      /**
       * Order
       * @description The order the subsection appears in the brand kit section. For example, if it is the first subsection,  `order` is `1`.
       * @example 1
       */
      order?: number | null;
      /**
       * Value
       * @description The new value or content of the updated subsection.
       * @example Example brand guideline update.
       */
      value?:
        | string
        | {
            [key: string]: unknown;
          }
        | unknown[]
        | null;
      /**
       * Intent
       * @description The intent or prompt that instructs the AI in populating this subsection and retrieving information from existing brand knowledge based on uploaded brand documents.
       * @example The core reason for the brand existence.
       */
      intent?: string | null;
      /**
       * Deletable
       * @description Whether the subsection can be deleted.
       * @default false
       * @example false
       */
      deletable: boolean | null;
      /**
       * Verified
       * @description Whether the subsection's content has been verified by the user.
       * @example true
       */
      verified?: boolean | null;
      /**
       * Createdon
       * @description The date and time when the subsection was created, formatted in ISO 8601.
       * @example 2025-06-18T12:46:12.718310Z
       */
      createdOn?: string | null;
      /**
       * Createdby
       * @description The user who created the subsection
       * @example mman
       */
      createdBy?: string | null;
      /**
       * Updatedon
       * @description The date and time when the subsection was updated, formatted in ISO 8601.
       * @example 2025-06-06T09:33:13.486417Z
       */
      updatedOn?: string | null;
      /**
       * Updatedby
       * @description The user who last updated the subsection.
       * @example mman
       */
      updatedBy?: string | null;
      /**
       * Aieditable
       * @description Whether the subsection can be edited by AI. If set to `true`, the AI will overwrite the subsection's content value when brand documents are reprocessed.
       * @example true
       */
      aiEditable?: boolean | null;
      /**
       * References
       * @description The brand documents the AI referenced to generate content for this subsection.
       */
      references: components["schemas"]["GetReferenceModelResponse"][] | null;
      /**
       * Properties
       * @description Additional properties for the subsection.
       */
      properties?: {
        [key: string]: unknown;
      } | null;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  list_brand_kits: {
    parameters: {
      query?: {
        pageNumber?: number;
        pageSize?: number;
        parentId?: string | null;
        status?: string | null;
        search?: string | null;
        referenceType?: string | null;
        referenceId?: string | null;
        includeDeleted?: boolean | null;
        brandkitIds?: string[] | null;
        sortBy?: components["schemas"]["SortByEnum"];
        sortType?: components["schemas"]["SortTypeEnum"];
      };
      header?: never;
      path: {
        organizationId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Brand kits retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ListBrandKitsModelResponse"];
        };
      };
      /** @description Unprocessable entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_brand_kit: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /**
         * @description The unique identifier of your organization.
         *
         *      To get this value, in the [Sitecore Cloud Portal](https://portal.sitecorecloud.io/) URL, the `organizationId` comes after `organization=`.
         */
        organizationId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateBrandKitModelRequest"];
      };
    };
    responses: {
      /** @description Brand kit created successfully */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CreateBrandKitModelResponse"];
        };
      };
      /** @description Duplicate brand kit name */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DuplicateHTTPError"];
        };
      };
      /** @description Unprocessable entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** @description Brand kit operation failed */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_brand_kit: {
    parameters: {
      query?: {
        includeDeleted?: boolean | null;
      };
      header?: never;
      path: {
        organizationId: string;
        brandkitId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Brand kit retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GetBrandKitModelResponse"];
        };
      };
      /** @description Unprocessable entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_brand_kit_sections: {
    parameters: {
      query?: {
        /** @description An array of section IDs to filter the results. If not provided, all sections in the brand kit are returned. */
        sectionIds?: string[] | null;
        /** @description Whether to include deleted sections in the response. */
        includeDeleted?: boolean | null;
      };
      header?: never;
      path: {
        /**
         * @description The unique identifier of your organization.
         *
         *      To get this value, in the [Sitecore Cloud Portal](https://portal.sitecorecloud.io/) URL, the `organizationId` comes after `organization=` .
         */
        organizationId: string;
        /**
         * @description The unique identifier of your brand kit.
         *
         *      To get this value, use the [List brand kits](#operation/list_brand_kits) endpoint  to return the `id` of each brand kit in your organization. This is the same `id` returned when you create a brand kit using the [Create a brand kit](#operation/create_brand_kit) endpoint.
         *
         *      Alternatively, you can open your brand kit in Stream. In the [Sitecore Cloud Portal](https://portal.sitecorecloud.io/) URL,  `brandkitId` comes after `brandkits/`.
         */
        brandkitId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Brand kit sections retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ListBrandKitSectionsModelResponse"][];
        };
      };
      /** @description Resource not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPError"];
        };
      };
      /** @description Unprocessable entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPError"];
        };
      };
      /** @description Brand kit operation failed */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_brand_kit_section_fields: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /**
         * @description The unique identifier of your organization.
         *
         *      To get this value, in the [Sitecore Cloud Portal](https://portal.sitecorecloud.io/) URL, the `organizationId` comes after `organization=` .
         */
        organizationId: string;
        /**
         * @description The unique identifier of your brand kit.
         *
         *      To get this value, use the [List brand kits](#operation/list_brand_kits) endpoint  to return the `id` of each brand kit in your organization. This is the same `id` returned when you create a brand kit using the [Create a brand kit](#operation/create_brand_kit) endpoint.
         *
         *      Alternatively, you can open your brand kit in Stream. In the [Sitecore Cloud Portal](https://portal.sitecorecloud.io/) URL,  `brandkitId` comes after `brandkits/`.
         */
        brandkitId: string;
        /**
         * @description The unique identifier of your brand kit section.
         *
         *      To get this value, use the [List brand kit sections](#operation/list_brand_kit_sections) endpoint. The `id` in the response is the section ID.
         */
        sectionId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Brand kit subsections retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ListBrandKitSectionFieldsModelResponse_v2"][];
        };
      };
      /** @description Unprocessable entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_brand_kit_section_field: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /**
         * @description The unique identifier of your organization.
         *
         *      To get this value, in the [Sitecore Cloud Portal](https://portal.sitecorecloud.io/) URL, the `organizationId` comes after `organization=` .
         */
        organizationId: string;
        /**
         * @description The unique identifier of your brand kit.
         *
         *      To get this value, use the [List brand kits](#operation/list_brand_kits) endpoint  to return the `id` of each brand kit in your organization. This is the same `id` returned when you create a brand kit using the [Create a brand kit](#operation/create_brand_kit) endpoint.
         *
         *      Alternatively, you can open your brand kit in Stream. In the [Sitecore Cloud Portal](https://portal.sitecorecloud.io/) URL,  `brandkitId` comes after `brandkits/`.
         */
        brandkitId: string;
        /**
         * @description The unique identifier of your brand kit section.
         *
         *      To get this value, use the [List brand kit sections](#operation/list_brand_kit_sections) endpoint. The `id` in the response is the section ID.
         */
        sectionId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateBrandKitSectionFieldModelRequest_v2"];
      };
    };
    responses: {
      /** @description Brand kit subsection created successfully */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CreateBrandKitSectionFieldModelResponse_v2"];
        };
      };
      /** @description Unprocessable entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_brand_kit_section_field: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /**
         * @description The unique identifier of your organization.
         *
         *      To get this value, in the [Sitecore Cloud Portal](https://portal.sitecorecloud.io/) URL, the `organizationId` comes after `organization=` .
         */
        organizationId: string;
        /**
         * @description The unique identifier of your brand kit.
         *
         *      To get this value, use the [List brand kits](#operation/list_brand_kits) endpoint  to return the `id` of each brand kit in your organization. This is the same `id` returned when you create a brand kit using the [Create a brand kit](#operation/create_brand_kit) endpoint.
         *
         *      Alternatively, you can open your brand kit in Stream. In the [Sitecore Cloud Portal](https://portal.sitecorecloud.io/) URL,  `brandkitId` comes after `brandkits/`.
         */
        brandkitId: string;
        /**
         * @description The unique identifier of your brand kit section.
         *
         *      To get this value, use the [List brand kit sections](#operation/list_brand_kit_sections) endpoint. The `id` in the response is the section ID.
         */
        sectionId: string;
        /**
         * @description The unique identifier of the brand kit subsection you want to update.
         *
         *      To get this value, use the [List brand kit subsections](#operation/list_brand_kit_section_fields) endpoint. The `id` in the response is the subsection ID.
         */
        fieldId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateBrandKitSectionFieldModelRequest_v2"];
      };
    };
    responses: {
      /** @description Brand kit subsection updated successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UpdateBrandKitSectionFieldModelResponse_v2"];
        };
      };
      /** @description Invalid parameters */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPError"];
        };
      };
      /** @description Resource not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPError"];
        };
      };
      /** @description Brand Kit is locked */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPError"];
        };
      };
      /** @description Unprocessable entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** @description Brand kit operation failed */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPError"];
        };
      };
    };
  };
}
