/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/data/v1/organizations/{organizationId}/pipeline/BrandIngestionPipeline": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Create a pipeline run for brand ingestion
     * @description Creates a new pipeline to run the brand ingestion process. Through this process, brand documents uploaded to a brand kit are processed, analyzed, and chunked into knowledge pieces to create brand knowledge.
     *
     *     To use this endpoint, make sure to upload and process at least one document before running the brand ingestion pipeline.
     *
     *     The brand ingestion process might take a few minutes depending on the file size.
     */
    post: operations["create_pipeline_run_brand_ingestion_api_data_v1_organizations__organizationId__pipeline_BrandIngestionPipeline_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/data/v1/organizations/{organizationId}/pipeline/EnrichSectionsPipeline": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Create a pipeline run for enrichment
     * @description Creates a new pipeline to run the enrichment process. This pipeline automatically retrieves information from your existing brand knowledge to generate or update the content of your brand kit sections and subsections.
     *
     *     To use this endpoint, make sure to upload and process at least one document before enriching the brand kit. If no brand knowledge is available, enrichment won’t run.
     *
     *      Additionally, if the subsection you want to enrich is marked as *non AI editable*, the content will not be modified.
     */
    post: operations["create_pipeline_run_enrich_sections_api_data_v1_organizations__organizationId__pipeline_EnrichSectionsPipeline_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** BrandIngestionPipelineParameters */
    BrandIngestionPipelineParameters: {
      /**
       * @description The unique identifier of your brand kit to be used for brand ingestion.
       *
       *      To get this value, use the [List brand kits](#operation/list_brand_kits_api_brands_v1_organizations__organizationId__brandkits_get) endpoint  to return the `id` of each brand kit in your organization. This is the same `id` returned when you create a brand kit using the [Create a brand kit](#operation/create_brand_kit_api_brands_v1_organizations__organizationId__brandkits_post) endpoint.
       *
       *      Alternatively, you can open your brand kit in Stream. In the [Sitecore Cloud Portal](https://portal.sitecorecloud.io/) URL,  the brand kit ID comes after `brandkits/`.
       * @example 98689dd5-1684-48cb-a339-d9610dbd7986
       */
      brand_kit_id?: string;
      /**
       * @description Whether to populate the brand kit sections with the ingested brand knowledge.
       *
       *      If you choose not to populate the sections, the brand documents will still be ingested. You can populate them later using the [Enrich sections](#operation/create_pipeline_run_enrich_sections_api_data_v1_organizations__organizationId__pipeline_EnrichSectionsPipeline_post) endpoint.
       * @default true
       * @example true
       */
      populateSections: boolean | null;
      /**
       * @description A comma-separated list of document IDs to be processed by the pipeline. Each ID represents a unique document, which you can retrieve using the [List documents](#tag/Document/operation/list_documents_v2_api_documents_v2_organizations__organizationId__documents_get) endpoint. The `id` field in the response contains the document ID.
       *
       *      If no IDs are provided, the pipeline will ingest all unprocessed documents in the brand kit.
       * @example 30e73070-5230-4441-a88e-ef72a7d15316,30e73070-5230-4441-a88e-ef72a7d15316
       */
      documentIdsList?: string | null;
    };
    /** CreatePipelineRunBrandIngestionRequest */
    CreatePipelineRunBrandIngestionRequest: {
      parameters: components["schemas"]["BrandIngestionPipelineParameters"];
    };
    /** CreatePipelineRunEnrichSectionsRequest */
    CreatePipelineRunEnrichSectionsRequest: {
      parameters: components["schemas"]["EnrichSectionsPipelineParameters"];
    };
    /** CreatePipelineRunResponse */
    CreatePipelineRunResponse: {
      /**
       * Format: date-time
       * @description The date and time when the pipeline run was created, formatted in ISO 8601.
       * @example 2025-04-23T13:55:13.308326
       */
      createdOn: string | null;
      /**
       * @description The user who created the pipeline run.
       * @example mman
       */
      createdBy: string | null;
      /**
       * Format: date-time
       * @description The date and time when the pipeline run was last updated, formatted in ISO 8601.
       * @example 2025-04-23T13:55:13.308326
       */
      updatedOn: string | null;
      /**
       * @description The user who last updated the pipeline run.
       * @example mman
       */
      updatedBy: string | null;
      /**
       * @description The unique identifier of the pipeline run.
       * @example e774b4b6-204e-11f0-a62d-3e62ff39b87e
       */
      id: string;
      /**
       * @description The name of the pipeline used to run a brand kit process.
       *
       *      Examples: `"BrandIngestionPipeline"`, `"EnrichSectionsPipeline"`.
       */
      pipelineId: string;
      /**
       * @description The parameters used for brand ingestion, such as brand kit and organization IDs and base URLs.
       * @example {
       *       "brand_kit_id": "98689dd5-1684-48cb-a339-d9610dbd7986",
       *       "org_id": "org_EXAMPLExxxxxxxx",
       *       "baseUrlDocAPI": "https://ai-documents-api-euw.sitecorecloud.io"
       *     }
       */
      parameters: {
        [key: string]: unknown;
      };
      /**
       * Format: date-time
       * @description The date and time when the pipeline run began, formatted in ISO 8601.
       * @example 2025-06-18T12:46:12.718310
       */
      runStart: string | null;
      /**
       * Format: date-time
       * @description The date and time when the pipeline run finished, formatted in ISO 8601.
       * @example 2025-06-18T12:46:12.718310
       */
      runEnd: string | null;
      /**
       * @description The total duration of the pipeline run in milliseconds.
       * @default 0
       * @example 3
       */
      durationInMs: number | null;
      /**
       * @description The current status of the pipeline run.
       * @example Succeeded
       * @enum {string|null}
       */
      status?: "Succeeded" | "Failed" | "Cancelled" | "InProgress" | "Queued" | "Canceling" | null;
      /**
       * @description Additional details or any error messages related to the pipeline run. This field is empty if no message is available.
       * @default
       * @example
       */
      message: string | null;
    };
    /** EnrichSectionsPipelineParameters */
    EnrichSectionsPipelineParameters: {
      /**
       * @description The unique identifier of your brand kit to enrich.
       *
       *      To get this value, use the [List brand kits](#operation/list_brand_kits_api_brands_v1_organizations__organizationId__brandkits_get) endpoint  to return the `id` of each brand kit in your organization. This is the same `id` returned when you create a brand kit using the [Create a brand kit](#operation/create_brand_kit_api_brands_v1_organizations__organizationId__brandkits_post) endpoint.
       *
       *      Alternatively, you can open your brand kit in Stream. In the [Sitecore Cloud Portal](https://portal.sitecorecloud.io/) URL,  the brand kit ID comes after `brandkits/`.
       *
       *      If you specify only a `brand_kit_id` without a `sectionId` or `fieldId`, the pipeline will enrich all unlocked sections and subsections in the brand kit.
       * @example 98689dd5-1684-48cb-a339-d9610dbd7986
       */
      brand_kit_id: string;
      /**
       * @description The unique identifier of the specific section of your brand kit to enrich.
       *
       *      If you provide only a `sectionId`, the pipeline will enrich all unlocked  subsections within that section.
       *
       *      To get the `sectionId`, use the [List brand kit sections](#operation/list_brand_kit_sections_api_brands_v1_organizations__organizationId__brandkits__brandkitId__sections_get) endpoint. The `id` in the response is the section ID.
       * @example b2f2e1a1-295d-4d40-88f2-93bf545bb878
       */
      sectionId?: string;
      /**
       * @description The unique identifier of the specific subsection of your brand kit to enrich. You can only enrich an unlocked subsection.
       *
       *      To enrich a specific subsection, you must specify both the `sectionId` and `fieldId`.
       *
       *      To get the `fieldId`, use the [List brand kit subsections](#operation/list_brand_kit_section_fields_api_brands_v2_organizations__organizationId__brandkits__brandkitId__sections__sectionId__fields_get) endpoint. The `id` in the response is the subsection ID.
       * @example b2f2e1a1-295d-4d40-88f2-93bf545bb878
       */
      fieldId?: string;
    };
    /** HTTPError */
    HTTPError: {
      /** Detail */
      detail: string;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  create_pipeline_run_brand_ingestion_api_data_v1_organizations__organizationId__pipeline_BrandIngestionPipeline_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        organizationId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreatePipelineRunBrandIngestionRequest"];
      };
    };
    responses: {
      /** @description Brand ingestion successfully ran */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CreatePipelineRunResponse"];
        };
      };
      /** @description Invalid request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPError"];
        };
      };
      /** @description Unprocessable entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** @description Brand kit ingestion failed */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPError"];
        };
      };
    };
  };
  create_pipeline_run_enrich_sections_api_data_v1_organizations__organizationId__pipeline_EnrichSectionsPipeline_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        organizationId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreatePipelineRunEnrichSectionsRequest"];
      };
    };
    responses: {
      /** @description Brand kit enrichment successfully ran */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CreatePipelineRunResponse"];
        };
      };
      /** @description Invalid request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPError"];
        };
      };
      /** @description Unprocessable entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** @description Brand kit enrichment failed */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPError"];
        };
      };
    };
  };
}
